USE MASTER

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'P@ssw0rd'
GO

CREATE CERTIFICATE SQL2_CERT
WITH SUBJECT='SQL2 ºÝÂI'
GO

CREATE ENDPOINT Ãè¹³
STATE = STARTED
AS TCP (LISTENER_PORT=5022
, LISTENER_IP = ALL)
	FOR DATABASE_MIRRORING (
	  AUTHENTICATION = CERTIFICATE SQL2_CERT
	  , ENCRYPTION = REQUIRED ALGORITHM AES
	  , ROLE = ALL )
GO

BACKUP CERTIFICATE SQL2_CERT
	TO FILE = 'c:\db\SQL2_CERT.cer'

	------------------------------------

CREATE CERTIFICATE SQL1_CERT
	AUTHORIZATION dbo
	FROM FILE = 'c:\db\SQL1_CERT.cer'
	GO


ALTER DATABASE [½m²ß18] SET PARTNER = 'TCP://SQL1:5022'
